CREATE TABLE MOVIE (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250),
  RELEASE VARCHAR(250),
  CENSORSHIP VARCHAR(250),
  DIRECTION VARCHAR(250)
);

CREATE TABLE CAST (
  ID  INT,
  ACTOR VARCHAR(250)
);
